### ISSUE TITLE
[Bug]: Clipboard crash Termux X11

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#740]
### Problem description

I noticed that if you press CTRL + C quickly, the Termux X11 shuts down.
Despite the debugging enabled, the log is short, but I hope this will help solve the problem

--------- beginning of crash
10-25 22:01:21.448  5396  5396 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7fd22f1b50 in tid 5396 (com.termux.x11), pid 5396 (com.termux.x11)

Didn't find anything interesting in logcat

### What steps will reproduce the bug?

CTRL + C many times quickly

**Comment by twaik** [comment]
Please, post full log.

**Comment by IntinteDAO** [comment]
I think it's a full log now
https://p.vinci-concessions.com/?6990eb72a4fa4f5d#71maJYAtG85J7BxF9FF194qGYoN6toJhDKRFb88tqxGD

**Comment by twaik** [comment]
Unfortunately, I can not reproduce it on my devices.

**Comment by twaik** [comment]
Is it still reproducible?

**Comment by IntinteDAO** [comment]
@twaik 

1) Clipboard sharing must be enabled. (I checked it)
2) By simply pressing ctrl + c, I was not able to invoke it, but just a small amount of text from the terminal invoked it. Maybe it's some kind of race condition that waits to receive data from the previous “clipboard”, and gets the next one, doesn't get the clipboard end mark, and a crash occurs. I don't know how the clipboard works, this is a hypothesis
3) Ugly log
https://paste.encrypt.co.il/?716afe82624393de#AtAuem1zznuftyuAw96s1YuKUPLyYJEd7yKkQVKgtKZW

4) It looks like you can cause a Crash loop in Termux X11 with this option, which will prevent Termux X11 from running, since (so I suspect) after the Android clipboard loads, it crashes.

**Comment by twaik** [comment]
Unfortunately I still can not reproduce it. Can you please post `termux-info` output? 
And btw how did you get log without normal line breaks?

**Comment by twaik** [comment]
Should be fixed in latest version. Can you please recheck it?

**Comment by IntinteDAO** [comment]
@twaik 

Not fixed. Maybe it can be related somehow with keyboard?
About line breaks - I just copy a log from Termux (also there is a little bug with terminal emulator I think) to nano

https://tube.midov.pl/w/9WjrNjY9GTfavZoRjQivBR
Sorry for useless talking XD

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7862
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root root stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous tur-multilib
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
ffmpeg/stable 6.1.2-2 aarch64 [upgradable from: 6.1.2-1]
layer-shell-qt/x11 6.2.4 aarch64 [upgradable from: 6.2.3]
libjxl/stable 0.11.1 aarch64 [upgradable from: 0.11.0]
qt5-qtbase-gtk-platformtheme/x11 5.15.16 aarch64 [upgradable from: 5.15.14-2]
qt5-qtbase/x11 5.15.16 aarch64 [upgradable from: 5.15.14-2]
qt5-qtdeclarative/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qtlocation/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qtmultimedia/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qtscript/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qtsensors/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qtserialport/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qtsvg/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qttools/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qtwebchannel/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qtwebsockets/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qtx11extras/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
qt5-qtxmlpatterns/x11 5.15.16 aarch64 [upgradable from: 5.15.14-1]
termux-tools version:
1.44.1
Android version:
14
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Mon Nov 18 21:23:53 UTC 2024 aarch64 Android
Device manufacturer:
motorola
Device model:
XT2125-4
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:15
```

**Comment by twaik** [comment]
Did you obtain this log with `TERMUX_X11_DEBUG=1`?
And please, output log to file. Copy-pasted log is not full and has no newlines which makes it very hard to read.

**Comment by IntinteDAO** [comment]
@twaik 

https://paste.momobako.com/?ef4ece8e1f21e7f4#Ea2Zk9JXBKZnv5jb8vsvJ8s5uhywwH6yXYdd5ZBKUuhD

It's directly saved to file, from x11 start to crash and running again

**Comment by twaik** [comment]
I wonder why it does not print full crashlog there.
I hardly believe I can debug your device this way. 
Probably it would be better to talk in realtime in discord or matrix and connect your device to debugger.
If you are in you are welcome to our matrix or discord servers.

**Comment by twaik** [comment]
@IntinteDAO can you please check if it is still reproducible?

**Comment by IntinteDAO** [comment]
@twaik It seems to be fine, but I will test until Sunday. If there is no feedback next week or I write that it is fine then close the issue

**Comment by IntinteDAO** [comment]
For now it works ok - I think it's fixed :) Closing
